"""Tests for scaffold.py (file creation, config generation)."""

import json
import pytest
from formal.scaffold import (
    create_ford_project_file,
    init_vitepress_site,
    inject_api_sidebar,
    _generate_config,
)


# ---------------------------------------------------------------------------
# create_ford_project_file
# ---------------------------------------------------------------------------

class TestCreateFordProjectFile:
    def test_basic_creation(self, tmp_path):
        out = tmp_path / "doc" / "formal.md"
        result = create_ford_project_file(
            output_path=out,
            project_name="MyProject",
            src_dirs=["../src"],
        )
        assert result == out
        assert out.exists()
        content = out.read_text()
        assert "project: MyProject" in content
        assert "src_dir: ../src" in content
        assert "docmark: <" in content
        assert "source: false" in content
        assert "warn: true" in content
        assert "graph: false" in content

    def test_parent_dirs_created(self, tmp_path):
        out = tmp_path / "deep" / "nested" / "file.md"
        create_ford_project_file(out, "Proj", ["../src"])
        assert out.exists()

    def test_multiline_src_dirs(self, tmp_path):
        out = tmp_path / "ford.md"
        create_ford_project_file(out, "Proj", ["../src/lib", "../src/app"])
        content = out.read_text()
        assert "src_dir: ../src/lib" in content
        assert "         ../src/app" in content

    def test_exclude_dirs(self, tmp_path):
        out = tmp_path / "ford.md"
        create_ford_project_file(out, "Proj", ["../src"], exclude_dirs=["third_party", "vendor"])
        content = out.read_text()
        assert "exclude_dir: third_party" in content
        assert "             vendor" in content

    def test_author(self, tmp_path):
        out = tmp_path / "ford.md"
        create_ford_project_file(out, "Proj", ["../src"], author="John Doe")
        content = out.read_text()
        assert "author: John Doe" in content

    def test_display_defaults(self, tmp_path):
        out = tmp_path / "ford.md"
        create_ford_project_file(out, "Proj", ["../src"])
        content = out.read_text()
        assert "display: public" in content
        assert "         protected" in content
        assert "         private" in content

    def test_extra_mods(self, tmp_path):
        out = tmp_path / "ford.md"
        create_ford_project_file(out, "Proj", ["../src"], extra_mods=["iso_fortran_env:http://example.com"])
        content = out.read_text()
        assert "extra_mods: iso_fortran_env:http://example.com" in content

    def test_body_text(self, tmp_path):
        out = tmp_path / "ford.md"
        create_ford_project_file(out, "MyLib", ["../src"])
        content = out.read_text()
        assert "MyLib API documentation -- generated by FORMAL." in content


# ---------------------------------------------------------------------------
# init_vitepress_site
# ---------------------------------------------------------------------------

class TestInitVitepressSite:
    def test_creates_all_files(self, tmp_path):
        docs = tmp_path / "docs"
        init_vitepress_site(docs, "TestProject")
        assert (docs / "package.json").exists()
        assert (docs / ".vitepress" / "config.mts").exists()
        assert (docs / "index.md").exists()
        assert (docs / "api").is_dir()

    def test_package_json_content(self, tmp_path):
        docs = tmp_path / "docs"
        init_vitepress_site(docs, "TestProject")
        pkg = json.loads((docs / "package.json").read_text())
        assert pkg["private"] is True
        assert "docs:dev" in pkg["scripts"]
        assert "vitepress" in pkg["devDependencies"]
        assert "markdown-it-mathjax3" in pkg["devDependencies"]

    def test_no_math(self, tmp_path):
        docs = tmp_path / "docs"
        init_vitepress_site(docs, "Proj", enable_math=False)
        pkg = json.loads((docs / "package.json").read_text())
        assert "markdown-it-mathjax3" not in pkg["devDependencies"]

    def test_skips_existing_files(self, tmp_path):
        docs = tmp_path / "docs"
        docs.mkdir()
        pkg_file = docs / "package.json"
        pkg_file.write_text('{"custom": true}')
        init_vitepress_site(docs, "Proj")
        # Should NOT overwrite
        assert json.loads(pkg_file.read_text()) == {"custom": True}

    def test_index_md_content(self, tmp_path):
        docs = tmp_path / "docs"
        init_vitepress_site(docs, "MyProject", description="A cool project")
        content = (docs / "index.md").read_text()
        assert "name: MyProject" in content
        assert "A cool project" in content
        assert "API Reference" in content

    def test_config_content(self, tmp_path):
        docs = tmp_path / "docs"
        init_vitepress_site(docs, "Proj")
        content = (docs / ".vitepress" / "config.mts").read_text()
        assert "defineConfig" in content
        assert "apiSidebar" in content


# ---------------------------------------------------------------------------
# inject_api_sidebar
# ---------------------------------------------------------------------------

class TestInjectApiSidebar:
    def test_adds_import(self, tmp_path):
        config = tmp_path / "config.mts"
        config.write_text("import { defineConfig } from 'vitepress'\n\nexport default defineConfig({})\n")
        result = inject_api_sidebar(config)
        assert result is True
        content = config.read_text()
        assert "import apiSidebar" in content

    def test_already_configured(self, tmp_path):
        config = tmp_path / "config.mts"
        config.write_text("import apiSidebar from '../api/_sidebar.json'\n\nexport default defineConfig({})\n")
        result = inject_api_sidebar(config)
        assert result is False

    def test_file_missing(self, tmp_path):
        config = tmp_path / "nonexistent.mts"
        result = inject_api_sidebar(config)
        assert result is False


# ---------------------------------------------------------------------------
# _generate_config
# ---------------------------------------------------------------------------

class TestGenerateConfig:
    def test_with_all_features(self):
        config = _generate_config("TestProj", "A description", enable_math=True, enable_fortran=True)
        assert "title: 'TestProj Documentation'" in config
        assert "description: 'A description'" in config
        assert "math: true" in config
        assert "fortran-free-form" in config
        assert "apiSidebar" in config

    def test_no_math(self):
        config = _generate_config("Proj", "", enable_math=False, enable_fortran=True)
        assert "math:" not in config
        assert "fortran-free-form" in config

    def test_no_fortran(self):
        config = _generate_config("Proj", "", enable_math=True, enable_fortran=False)
        assert "math: true" in config
        assert "fortran" not in config.split("languages")[0] if "languages" in config else True
        assert "languageAlias" not in config

    def test_no_description(self):
        config = _generate_config("Proj", "", enable_math=False, enable_fortran=False)
        assert "description:" not in config
