"""VitePress site scaffolding and FORD project file generation.

Creates the minimal VitePress structure and config needed to host
auto-generated API documentation alongside hand-written pages.
"""

import json
from pathlib import Path
from typing import Optional


def create_ford_project_file(
    output_path: Path,
    project_name: str,
    src_dirs: list[str],
    exclude_dirs: Optional[list[str]] = None,
    docmark: str = "<",
    display: Optional[list[str]] = None,
    author: str = "",
    extra_mods: Optional[list[str]] = None,
) -> Path:
    """Generate a FORD project file (.md) for source parsing.

    Args:
        output_path: Where to write the project file.
        project_name: Name of the Fortran project.
        src_dirs: List of source directories (relative to project file location).
        exclude_dirs: Directories to exclude from parsing.
        docmark: FORD doc comment marker (default '<' for '!<' comments).
        display: Visibility levels to include (default: public, protected, private).
        author: Author name.
        extra_mods: Extra module references (e.g. 'iso_fortran_env:URL').

    Returns:
        Path to the created project file.
    """
    if display is None:
        display = ["public", "protected", "private"]
    if exclude_dirs is None:
        exclude_dirs = []

    lines = []
    lines.append(f"project: {project_name}")

    # src_dir with multiline alignment
    lines.append(f"src_dir: {src_dirs[0]}")
    for d in src_dirs[1:]:
        lines.append(f"         {d}")

    if exclude_dirs:
        lines.append(f"exclude_dir: {exclude_dirs[0]}")
        for d in exclude_dirs[1:]:
            lines.append(f"             {d}")

    lines.append("output_dir: /tmp/formal_ford_out")

    if author:
        lines.append(f"author: {author}")

    lines.append(f"docmark: {docmark}")

    lines.append(f"display: {display[0]}")
    for d in display[1:]:
        lines.append(f"         {d}")

    lines.append("source: false")
    lines.append("warn: true")
    lines.append("graph: false")

    if extra_mods:
        lines.append(f"extra_mods: {extra_mods[0]}")
        for m in extra_mods[1:]:
            lines.append(f"            {m}")

    lines.append("")
    lines.append(f"{project_name} API documentation -- generated by FORMAL.")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def init_vitepress_site(
    docs_dir: Path,
    project_name: str,
    description: str = "",
    enable_math: bool = True,
    enable_fortran: bool = True,
    enable_mermaid: bool = False,
) -> None:
    """Scaffold a minimal VitePress docs site if one doesn't already exist.

    Creates package.json, .vitepress/config.mts, and a landing index.md.
    Skips files that already exist to avoid overwriting customizations.

    Args:
        docs_dir: The docs/ directory to scaffold into.
        project_name: Project name for titles and headings.
        description: Short project description.
        enable_math: Include markdown-it-mathjax3 and math config.
        enable_fortran: Include Fortran syntax highlighting aliases.
        enable_mermaid: Include vitepress-plugin-mermaid and wrap config with
            ``withMermaid`` so that fenced Mermaid blocks render in the browser.
    """
    docs_dir.mkdir(parents=True, exist_ok=True)

    # package.json
    pkg_file = docs_dir / "package.json"
    if not pkg_file.exists():
        deps = {"vitepress": "^1.6.3"}
        if enable_math:
            deps["markdown-it-mathjax3"] = "^4.3.2"
        if enable_mermaid:
            deps["vitepress-plugin-mermaid"] = "^2.0.0"
            deps["mermaid"] = "^11.0.0"

        pkg = {
            "private": True,
            "scripts": {
                "docs:api": "formal generate",
                "docs:dev": "vitepress dev",
                "docs:build": "vitepress build",
                "docs:preview": "vitepress preview",
            },
            "devDependencies": deps,
        }
        pkg_file.write_text(json.dumps(pkg, indent=2) + "\n", encoding="utf-8")
        print(f"  Created {pkg_file}")

    # .vitepress/config.mts
    config_dir = docs_dir / ".vitepress"
    config_dir.mkdir(exist_ok=True)
    config_file = config_dir / "config.mts"
    if not config_file.exists():
        config_file.write_text(
            _generate_config(project_name, description, enable_math, enable_fortran, enable_mermaid),
            encoding="utf-8",
        )
        print(f"  Created {config_file}")

    # index.md
    index_file = docs_dir / "index.md"
    if not index_file.exists():
        index_content = f"""---
layout: home

hero:
  name: {project_name}
  text: Documentation
  tagline: {description or 'Auto-generated API documentation for Fortran sources'}
  actions:
    - theme: brand
      text: API Reference
      link: /api/

features:
  - title: API Reference
    details: Auto-generated from Fortran source doc comments.
---
"""
        index_file.write_text(index_content, encoding="utf-8")
        print(f"  Created {index_file}")

    # api/ directory placeholder
    api_dir = docs_dir / "api"
    api_dir.mkdir(exist_ok=True)


def _generate_config(
    project_name: str,
    description: str,
    enable_math: bool,
    enable_fortran: bool,
    enable_mermaid: bool = False,
) -> str:
    """Generate VitePress config.mts content."""
    lines = []
    if enable_mermaid:
        lines.append("import { withMermaid } from 'vitepress-plugin-mermaid'")
    else:
        lines.append("import { defineConfig } from 'vitepress'")
    lines.append("import apiSidebar from '../api/_sidebar.json'")
    lines.append("")
    wrapper = "withMermaid" if enable_mermaid else "defineConfig"
    lines.append(f"export default {wrapper}({{")
    lines.append(f"  title: '{project_name} Documentation',")
    if description:
        lines.append(f"  description: '{description}',")
    lines.append("  markdown: {")
    if enable_math:
        lines.append("    math: true,")
    if enable_fortran:
        lines.append("    languages: ['fortran-free-form', 'fortran-fixed-form'],")
        lines.append("    languageAlias: {")
        lines.append("      'fortran': 'fortran-free-form',")
        lines.append("      'f90': 'fortran-free-form',")
        lines.append("      'f95': 'fortran-free-form',")
        lines.append("      'f03': 'fortran-free-form',")
        lines.append("      'f08': 'fortran-free-form',")
        lines.append("      'f77': 'fortran-fixed-form',")
        lines.append("    },")
    lines.append("  },")
    lines.append("  themeConfig: {")
    lines.append("    nav: [")
    lines.append(f"      {{ text: 'Home', link: '/' }},")
    lines.append(f"      {{ text: 'API', link: '/api/' }},")
    lines.append("    ],")
    lines.append("    sidebar: {")
    lines.append("      '/api/': [")
    lines.append("        {")
    lines.append("          text: 'API Reference',")
    lines.append("          items: [")
    lines.append("            { text: 'Overview', link: '/api/' },")
    lines.append("          ],")
    lines.append("        },")
    lines.append("        ...apiSidebar,")
    lines.append("      ],")
    lines.append("    },")
    lines.append("    search: {")
    lines.append("      provider: 'local',")
    lines.append("    },")
    lines.append("  },")
    if enable_mermaid:
        lines.append("  mermaid: {},")
    lines.append("})")
    lines.append("")
    return "\n".join(lines)


def inject_api_sidebar(config_file: Path) -> bool:
    """Add API sidebar import to an existing VitePress config.mts.

    Checks if the import and sidebar section already exist. If not, adds them.

    Args:
        config_file: Path to .vitepress/config.mts.

    Returns:
        True if the file was modified, False if already configured.
    """
    if not config_file.exists():
        return False

    content = config_file.read_text(encoding="utf-8")

    if "apiSidebar" in content:
        return False  # already configured

    # Add import at the top
    if "import apiSidebar" not in content:
        content = "import apiSidebar from '../api/_sidebar.json'\n" + content

    print(f"  Updated {config_file} (added apiSidebar import)")
    print("  Note: You need to manually add the API sidebar section to your config.")
    print("  See: https://github.com/szaghi/formal#existing-vitepress-site")
    config_file.write_text(content, encoding="utf-8")
    return True
